server:
  port: 8083

spring:
  config:
    import: .env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    url: ${DB_URL}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    parameters:
      admin:
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
